export type ToolCategory = 'CRM' | 'SEO & GEO' | 'Email Marketing' | 'Analytics' | 'Automation' | 'AI Writing' | 'Design & Brand' | 'Scheduling';

export interface Tool {
    id: string;
    name: string;
    emoji: string;
    initials: string;
    tagline: string;
    summary: string;
    bestFor: string;
    whyWeRecommend: string;
    category: ToolCategory;
    affiliateUrl: string;
    accentColor: string;
    implementationCta: string;
}

export const tools: Tool[] = [
    {
        id: 'hubspot',
        name: 'HubSpot',
        emoji: '🟠',
        initials: 'HS',
        tagline: 'The all-in-one CRM for growing teams',
        summary: 'HubSpot combines CRM, marketing automation, sales pipelines, and customer service in one platform. Its free tier is genuinely powerful — and scales cleanly as you grow.',
        bestFor: 'Growing teams wanting an all-in-one platform',
        whyWeRecommend: 'We have deployed HubSpot across 40+ client accounts. The native integrations, reporting, and ease of onboarding make it the default choice for teams under 200 people.',
        category: 'CRM',
        affiliateUrl: '#',
        accentColor: '#FF7A59',
        implementationCta: 'Get HubSpot set up for you',
    },
    {
        id: 'pipedrive',
        name: 'Pipedrive',
        emoji: '🟢',
        initials: 'PD',
        tagline: 'Sales-first CRM built for closing',
        summary: 'Pipedrive is a visual pipeline CRM designed by salespeople, for salespeople. Less marketing fluff, more deal-closing focus — and at a fraction of HubSpot\'s cost.',
        bestFor: 'Sales-focused SMBs who want pipeline clarity',
        whyWeRecommend: 'When a client\'s primary goal is managing a high-volume sales pipeline rather than marketing automation, Pipedrive wins every time on simplicity and value.',
        category: 'CRM',
        affiliateUrl: '#',
        accentColor: '#00C85C',
        implementationCta: 'Get Pipedrive configured for your team',
    },
    {
        id: 'ahrefs',
        name: 'Ahrefs',
        emoji: '🔵',
        initials: 'AH',
        tagline: 'The gold standard for serious SEO',
        summary: 'Ahrefs offers the most comprehensive backlink database, keyword research tools, and content analysis in the industry. If you\'re building a content moat, this is your weapon.',
        bestFor: 'Serious content teams building long-term organic authority',
        whyWeRecommend: 'We use Ahrefs daily for content gap analysis, competitor research, and tracking our clients\' keyword portfolios. The depth of data is unmatched.',
        category: 'SEO & GEO',
        affiliateUrl: '#',
        accentColor: '#1B6AC9',
        implementationCta: 'Have us build your SEO strategy with Ahrefs',
    },
    {
        id: 'semrush',
        name: 'Semrush',
        emoji: '🟡',
        initials: 'SR',
        tagline: 'The Swiss Army knife for digital marketing',
        summary: 'Semrush covers SEO, PPC, content marketing, social media, and competitive intelligence. The breadth makes it the go-to for agencies managing multiple client channels.',
        bestFor: 'Agencies managing SEO, paid, and content across multiple clients',
        whyWeRecommend: 'The ability to manage multiple projects, track competitors across channels, and generate client reports from one tool makes Semrush indispensable for agencies.',
        category: 'SEO & GEO',
        affiliateUrl: '#',
        accentColor: '#FF642D',
        implementationCta: 'Let us run your agency SEO on Semrush',
    },
    {
        id: 'surfer-seo',
        name: 'Surfer SEO',
        emoji: '🌊',
        initials: 'SF',
        tagline: 'AI-optimized content scoring in real time',
        summary: 'Surfer analyses the top-ranking pages for your target keyword and tells you exactly how to optimise your content — from word count to semantic keywords. Built for AI-era content.',
        bestFor: 'Teams creating AI-assisted, SEO-optimised content at scale',
        whyWeRecommend: 'Surfer is the fastest way to write content that ranks. We integrate it into our content workflows to ensure every article is structurally sound before publishing.',
        category: 'SEO & GEO',
        affiliateUrl: '#',
        accentColor: '#7B68EE',
        implementationCta: 'Get Surfer integrated into your content workflow',
    },
    {
        id: 'mailchimp',
        name: 'Mailchimp',
        emoji: '🐒',
        initials: 'MC',
        tagline: 'The easiest email platform to start with',
        summary: 'Mailchimp is the world\'s most recognised email marketing platform. Simple, visual, and with a generous free tier. Perfect for getting your first campaigns off the ground.',
        bestFor: 'Beginners and small businesses starting email marketing',
        whyWeRecommend: 'For clients new to email marketing, Mailchimp reduces friction. The drag-and-drop builder, templates, and automation basics mean you can send your first campaign within an hour.',
        category: 'Email Marketing',
        affiliateUrl: '#',
        accentColor: '#FFE01B',
        implementationCta: 'Get your first email sequence built',
    },
    {
        id: 'convertkit',
        name: 'ConvertKit',
        emoji: '✉️',
        initials: 'CK',
        tagline: 'Email built for creators and founders',
        summary: 'ConvertKit (now Kit) is designed for knowledge businesses, consultants, and founders. Powerful automations, clean landing pages, and a subscriber-first philosophy.',
        bestFor: 'Creators, consultants, and founder-led businesses',
        whyWeRecommend: 'When a founder wants to build a genuine audience relationship rather than blast promotions, ConvertKit\'s tagging and sequence system is perfect.',
        category: 'Email Marketing',
        affiliateUrl: '#',
        accentColor: '#FB6970',
        implementationCta: 'Get your ConvertKit funnel built',
    },
    {
        id: 'klaviyo',
        name: 'Klaviyo',
        emoji: '🟣',
        initials: 'KL',
        tagline: 'Revenue-focused email for eCommerce',
        summary: 'Klaviyo is the email and SMS platform built for eCommerce. Deep Shopify integration, revenue attribution, and behavioural automation make it the clear eCommerce winner.',
        bestFor: 'eCommerce brands wanting data-driven email automation',
        whyWeRecommend: 'If you\'re running Shopify, Klaviyo pays for itself within weeks. The predictive analytics and abandoned cart flows alone typically generate 20-30% of client revenue.',
        category: 'Email Marketing',
        affiliateUrl: '#',
        accentColor: '#5E4CE6',
        implementationCta: 'Get your Klaviyo flows configured',
    },
    {
        id: 'google-analytics-4',
        name: 'Google Analytics 4',
        emoji: '📊',
        initials: 'GA',
        tagline: 'The universal analytics baseline',
        summary: 'GA4 is the free, event-based analytics platform from Google. Essential for tracking user behaviour, conversions, and marketing attribution across your entire digital presence.',
        bestFor: 'All businesses — a non-negotiable baseline',
        whyWeRecommend: 'We configure GA4 properly for every client from day one. Most installs are misconfigured — we fix that. Proper event tracking transforms your ability to make data-driven decisions.',
        category: 'Analytics',
        affiliateUrl: '#',
        accentColor: '#E37400',
        implementationCta: 'Get GA4 configured properly for your site',
    },
    {
        id: 'hotjar',
        name: 'Hotjar',
        emoji: '🔥',
        initials: 'HJ',
        tagline: 'See exactly how users interact with your site',
        summary: 'Hotjar provides heatmaps, session recordings, and feedback surveys that reveal why users do what they do. Essential for any CRO initiative.',
        bestFor: 'Teams running conversion rate optimisation',
        whyWeRecommend: 'Before any redesign or CRO project, we install Hotjar. The session recordings alone reveal friction points that no amount of analytics data can show.',
        category: 'Analytics',
        affiliateUrl: '#',
        accentColor: '#FD3A5C',
        implementationCta: 'Get Hotjar set up for CRO research',
    },
    {
        id: 'mixpanel',
        name: 'Mixpanel',
        emoji: '📈',
        initials: 'MX',
        tagline: 'Product analytics for SaaS teams',
        summary: 'Mixpanel is the product analytics platform for SaaS businesses. Track feature adoption, user retention, and funnel drop-off with granular, event-based reporting.',
        bestFor: 'SaaS products tracking user behaviour and retention',
        whyWeRecommend: 'For product-led growth companies, Mixpanel provides the depth of insight that GA4 cannot. Retention curves and cohort analysis are game-changers for product decisions.',
        category: 'Analytics',
        affiliateUrl: '#',
        accentColor: '#7856FF',
        implementationCta: 'Get Mixpanel instrumented in your product',
    },
    {
        id: 'make',
        name: 'Make.com',
        emoji: '⚙️',
        initials: 'MK',
        tagline: 'Visual no-code automation for complex workflows',
        summary: 'Make (formerly Integromat) is the most powerful visual automation builder for complex, multi-step workflows. Handles edge cases and data transformation that Zapier cannot.',
        bestFor: 'No-code teams building complex, data-heavy workflows',
        whyWeRecommend: 'We build most of our client automations on Make. The visual workflow builder, error handling, and pricing per operation (not per zap) make it far more powerful and cost-efficient.',
        category: 'Automation',
        affiliateUrl: '#',
        accentColor: '#6D00CC',
        implementationCta: 'Get your automations built on Make',
    },
    {
        id: 'zapier',
        name: 'Zapier',
        emoji: '⚡',
        initials: 'ZP',
        tagline: 'The fastest way to connect your apps',
        summary: 'Zapier is the gold standard for quick, reliable integrations. 6,000+ app connections and a no-code interface mean you can automate simple workflows in minutes.',
        bestFor: 'Quick integrations between mainstream SaaS tools',
        whyWeRecommend: 'For simple trigger-action workflows where speed of setup matters more than complexity, Zapier is unbeatable. We use it to bridge tools while more robust systems are built.',
        category: 'Automation',
        affiliateUrl: '#',
        accentColor: '#FF4A00',
        implementationCta: 'Get your Zapier workflows set up',
    },
    {
        id: 'n8n',
        name: 'n8n',
        emoji: '🔧',
        initials: 'N8',
        tagline: 'Self-hosted automation with full data control',
        summary: 'n8n is an open-source workflow automation tool that you can self-host. Full data sovereignty, unlimited workflows, and deep custom logic capability for technical teams.',
        bestFor: 'Technical teams and businesses with data compliance needs',
        whyWeRecommend: 'For clients with strict data requirements or complex custom workflows, n8n provides the power of Make with full control over where data is stored and processed.',
        category: 'Automation',
        affiliateUrl: '#',
        accentColor: '#EA4B71',
        implementationCta: 'Get n8n deployed and configured',
    },
    {
        id: 'jasper',
        name: 'Jasper',
        emoji: '✨',
        initials: 'JS',
        tagline: 'AI writing built for marketing teams',
        summary: 'Jasper is an AI writing platform designed specifically for marketing copy — ads, emails, blogs, and social content. It includes brand voice training and campaign workflows.',
        bestFor: 'Marketing teams producing high volumes of branded content',
        whyWeRecommend: 'When a client needs to scale content production without losing brand consistency, Jasper\'s brand voice feature and pre-built marketing templates save significant time.',
        category: 'AI Writing',
        affiliateUrl: '#',
        accentColor: '#7C3AED',
        implementationCta: 'Get your brand voice set up in Jasper',
    },
    {
        id: 'claude',
        name: 'Claude',
        emoji: '🤖',
        initials: 'CL',
        tagline: 'The best AI for strategy and long-form thinking',
        summary: 'Claude by Anthropic excels at nuanced, long-form content — strategy documents, positioning decks, and detailed analysis. Its reasoning capability is unmatched for complex briefs.',
        bestFor: 'Long-form strategy content, proposals, and analysis',
        whyWeRecommend: 'We use Claude daily for strategy work, client proposals, and content that requires genuine depth. It understands context and nuance better than any other model for written work.',
        category: 'AI Writing',
        affiliateUrl: '#',
        accentColor: '#D4A96A',
        implementationCta: 'Get Claude integrated into your content workflow',
    },
    {
        id: 'perplexity',
        name: 'Perplexity',
        emoji: '🔎',
        initials: 'PX',
        tagline: 'AI-powered research with real-time sources',
        summary: 'Perplexity is an AI answer engine that cites its sources and searches the web in real time. Exceptional for competitive research, market intelligence, and fact-checked writing.',
        bestFor: 'Research-heavy content and competitive intelligence',
        whyWeRecommend: 'For any content that requires current data, industry research, or competitor analysis, Perplexity dramatically reduces research time while improving accuracy.',
        category: 'AI Writing',
        affiliateUrl: '#',
        accentColor: '#20B2AA',
        implementationCta: 'Integrate research into your content process',
    },
    {
        id: 'canva',
        name: 'Canva',
        emoji: '🎨',
        initials: 'CV',
        tagline: 'Design for everyone, in minutes',
        summary: 'Canva is the world\'s most accessible design tool. Templates, brand kits, AI image generation, and collaborative editing — all without needing a design background.',
        bestFor: 'Non-designers and teams needing fast, on-brand visuals',
        whyWeRecommend: 'We build Canva Brand Kits for clients so their whole team can create consistent, on-brand assets without design bottlenecks. It scales design capacity without scaling headcount.',
        category: 'Design & Brand',
        affiliateUrl: '#',
        accentColor: '#00C4CC',
        implementationCta: 'Get your Canva brand kit built',
    },
    {
        id: 'figma',
        name: 'Figma',
        emoji: '🖌️',
        initials: 'FG',
        tagline: 'The industry standard for professional design',
        summary: 'Figma is the collaborative design tool of choice for product designers, UI/UX teams, and agencies. Real-time collaboration, component libraries, and developer handoff built in.',
        bestFor: 'Design teams building products, websites, and design systems',
        whyWeRecommend: 'Every pixel of our design work lives in Figma. It enables seamless collaboration between our designers, developers, and clients — and the component system keeps designs consistent at scale.',
        category: 'Design & Brand',
        affiliateUrl: '#',
        accentColor: '#F24E1E',
        implementationCta: 'Get your design system built in Figma',
    },
    {
        id: 'calendly',
        name: 'Calendly',
        emoji: '📅',
        initials: 'CY',
        tagline: 'The easiest way to book meetings',
        summary: 'Calendly eliminates the back-and-forth of scheduling by letting prospects book directly into your calendar. Integrates with CRMs, video tools, and payment processors.',
        bestFor: 'Consultants, sales teams, and service businesses',
        whyWeRecommend: 'We embed Calendly on every client\'s website as a core conversion point. A well-configured booking page with reminder sequences typically increases show rates by 30-40%.',
        category: 'Scheduling',
        affiliateUrl: '#',
        accentColor: '#006BFF',
        implementationCta: 'Get your booking workflow optimised',
    },
    {
        id: 'cal-com',
        name: 'Cal.com',
        emoji: '📆',
        initials: 'CC',
        tagline: 'Open-source scheduling with full control',
        summary: 'Cal.com is the open-source alternative to Calendly. Self-hostable, fully customisable, and built for teams who want scheduling infrastructure they own and control.',
        bestFor: 'Businesses preferring open-source and data sovereignty',
        whyWeRecommend: 'For clients who want to self-host their scheduling or need deep customisation that Calendly\'s plans don\'t allow, Cal.com delivers the same core experience with full flexibility.',
        category: 'Scheduling',
        affiliateUrl: '#',
        accentColor: '#111827',
        implementationCta: 'Get Cal.com deployed for your team',
    },
];

export const toolCategories: ToolCategory[] = [
    'CRM',
    'SEO & GEO',
    'Email Marketing',
    'Analytics',
    'Automation',
    'AI Writing',
    'Design & Brand',
    'Scheduling',
];

export function getToolsByCategory(category: ToolCategory): Tool[] {
    return tools.filter(t => t.category === category);
}
