export type ResourceCategory = 'Guide' | 'Template' | 'Calculator' | 'Comparison' | 'Case Study' | 'Insight';

export interface Resource {
    id: string;
    title: string;
    description: string;
    category: ResourceCategory;
    icon: string;
    readTime: string;
    href: string;
    featured?: boolean;
    badge?: string;
}

export const resources: Resource[] = [
    {
        id: 'b2b-website-growth-system-2026',
        title: 'B2B Website Growth System 2026',
        description: 'The complete framework for turning your website into a revenue-generating engine. Covers CRO, SEO, GEO, and conversion architecture for modern B2B buyers.',
        category: 'Guide',
        icon: '📈',
        readTime: '18 min read',
        href: '/playbooks/b2b-growth-system-2026',
        featured: true,
        badge: 'Most Popular',
    },
    {
        id: 'ai-search-optimization-checklist',
        title: 'AI Search Optimization Checklist',
        description: 'A step-by-step checklist to make your content discoverable in AI-powered search engines like Perplexity, ChatGPT Search, and Google AI Overviews.',
        category: 'Guide',
        icon: '🤖',
        readTime: '12 min read',
        href: '/playbooks/ai-search-optimization-guide',
        featured: true,
        badge: 'New',
    },
    {
        id: 'brand-positioning-framework',
        title: 'Brand Positioning Framework',
        description: 'Define your market position, craft your unique value proposition, and build messaging that resonates with your ideal clients — even in saturated markets.',
        category: 'Guide',
        icon: '🎯',
        readTime: '15 min read',
        href: '/resources/brand-positioning-framework',
        featured: true,
    },
    {
        id: 'content-hub-planning-guide',
        title: 'Content Hub Planning Guide',
        description: 'How to plan, structure, and launch a content hub that builds topical authority, captures organic traffic, and converts readers into leads.',
        category: 'Guide',
        icon: '📚',
        readTime: '14 min read',
        href: '/resources/content-hub-planning-guide',
    },
    {
        id: 'homepage-cro-teardown-framework',
        title: 'Homepage CRO Teardown Framework',
        description: 'The exact framework we use to audit and rewrite homepage copy and layout. Includes before/after examples and a 50-point conversion checklist.',
        category: 'Guide',
        icon: '🔍',
        readTime: '20 min read',
        href: '/resources/homepage-cro-teardown',
    },
    {
        id: 'website-growth-audit-checklist',
        title: 'Website Growth Audit Checklist',
        description: 'A downloadable 80-point audit covering speed, SEO, conversion, messaging, and UX. Used by 2,400+ growth teams to identify revenue leaks.',
        category: 'Template',
        icon: '✅',
        readTime: '5 min download',
        href: '/lead-magnets/website-audit-checklist',
        badge: 'Free Download',
    },
    {
        id: 'marketing-stack-audit-worksheet',
        title: 'Marketing Stack Audit Worksheet',
        description: 'Map your current marketing tools, identify gaps and redundancies, and build a leaner, more effective growth stack with this structured worksheet.',
        category: 'Template',
        icon: '📋',
        readTime: '10 min setup',
        href: '/resources/marketing-stack-audit',
    },
    {
        id: 'homepage-wireframe-checklist',
        title: 'Homepage Wireframe Checklist',
        description: 'The 12 essential sections every high-converting homepage needs, with copy prompts, layout guidance, and common mistakes to avoid.',
        category: 'Template',
        icon: '🖼️',
        readTime: '8 min read',
        href: '/resources/homepage-wireframe-checklist',
    },
    {
        id: 'service-page-messaging-framework',
        title: 'Service Page Messaging Framework',
        description: 'A fill-in-the-blank messaging template for service pages that converts. Covers positioning, proof, objections, and CTA hierarchy.',
        category: 'Template',
        icon: '✍️',
        readTime: '10 min read',
        href: '/resources/service-page-messaging',
    },
    {
        id: 'b2b-lead-magnet-planning-template',
        title: 'B2B Lead Magnet Planning Template',
        description: 'From concept to launch: plan, design, and promote a lead magnet that attracts qualified B2B prospects using this structured planning doc.',
        category: 'Template',
        icon: '🧲',
        readTime: '12 min read',
        href: '/resources/lead-magnet-planning-template',
    },
    {
        id: 'roi-calculator',
        title: 'ROI Calculator',
        description: 'Calculate your exact growth potential: input your traffic, conversion rate, and deal value to see your revenue upside in 3, 6, and 12 months.',
        category: 'Calculator',
        icon: '🧮',
        readTime: '2 min to use',
        href: '/tools/roi',
        badge: 'Interactive',
    },
    {
        id: 'content-roi-calculator',
        title: 'Content ROI Calculator',
        description: 'Estimate the long-term ROI of your content marketing investment — factoring in traffic, lead conversion, deal value, and content lifecycle.',
        category: 'Calculator',
        icon: '📊',
        readTime: '3 min to use',
        href: '/tools/roi',
        badge: 'Interactive',
    },
    {
        id: 'growth-readiness-score',
        title: 'Growth Readiness Score',
        description: 'A 12-question diagnostic that scores your business across 6 growth dimensions. Get a personalised action plan based on your results.',
        category: 'Calculator',
        icon: '⚡',
        readTime: '4 min assessment',
        href: '/tools/readiness-quiz',
        badge: 'Interactive',
    },
    {
        id: 'hubspot-vs-pipedrive',
        title: 'HubSpot vs Pipedrive for B2B',
        description: 'An in-depth feature-by-feature comparison of the two most popular CRMs for B2B teams. Includes pricing, use cases, and a clear verdict.',
        category: 'Comparison',
        icon: '⚖️',
        readTime: '10 min read',
        href: '/compare/hubspot-vs-pipedrive',
    },
    {
        id: 'notion-vs-airtable',
        title: 'Notion vs Airtable for Marketing Teams',
        description: 'Which is better for managing content calendars, campaigns, and marketing ops? A practical comparison with real use-case scenarios.',
        category: 'Comparison',
        icon: '⚖️',
        readTime: '9 min read',
        href: '/compare/notion-vs-airtable',
    },
    {
        id: 'webflow-vs-wordpress',
        title: 'Webflow vs WordPress for Agencies',
        description: 'The definitive comparison for agency owners choosing between Webflow and WordPress. Covers speed, CMS, scalability, cost, and client handoff.',
        category: 'Comparison',
        icon: '⚖️',
        readTime: '11 min read',
        href: '/compare/webflow-vs-wordpress',
    },
    {
        id: 'case-study-3x-inbound-leads',
        title: 'How We 3x-ed Inbound Leads for a SaaS Brand',
        description: 'A full teardown of the 90-day content and CRO strategy that tripled monthly inbound leads for a B2B SaaS company, from 47 to 142 leads/month.',
        category: 'Case Study',
        icon: '📁',
        readTime: '14 min read',
        href: '/resources/case-study-saas-inbound-leads',
        badge: 'Featured',
    },
    {
        id: 'case-study-bounce-rate',
        title: 'Website Redesign That Cut Bounce Rate by 40%',
        description: 'The messaging, structure, and UX changes we made to a professional services website that reduced bounce rate from 74% to 44% in 60 days.',
        category: 'Case Study',
        icon: '📁',
        readTime: '12 min read',
        href: '/resources/case-study-bounce-rate-redesign',
    },
    {
        id: 'why-geo-will-replace-seo-2026',
        title: 'Why GEO Will Replace SEO in 2026',
        description: 'Generative Engine Optimisation is not a buzzword — it is the new game. Here is what it means, why it matters, and the 7 tactics to implement now.',
        category: 'Insight',
        icon: '💡',
        readTime: '9 min read',
        href: '/insights/automation-guide',
        badge: 'Trending',
    },
    {
        id: 'death-of-generic-agency-websites',
        title: 'The Death of Generic Agency Websites',
        description: 'Why templated agency websites are losing business to specialist competitors, and the positioning strategy that lets smaller agencies win against bigger names.',
        category: 'Insight',
        icon: '💡',
        readTime: '7 min read',
        href: '/insights/branding-2025',
    },
];

export const featuredResources = resources.filter(r => r.featured);

export const categories: ResourceCategory[] = ['Guide', 'Template', 'Calculator', 'Comparison', 'Case Study', 'Insight'];
