// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
    hero: dynamic(() => import("./Hero")),
    bento_grid: dynamic(() => import("./BentoGrid")),
    services: dynamic(() => import("./Services")),
};
